name: Android Kernel 5.15 Build with Bazel

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
            run: |
                sudo apt-get update
                sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev gcc-aarch64-linux-gnu bazel
        - name: Setup environment
            run: |
                export ARCH=arm64
                export SUBARCH=arm64
                export CROSS_COMPILE=aarch64-linux-gnu-
        - name: Run setup script
            run: |
                curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
        - name: Configure kernel
            run: |
                cd android-kernel-5.15
                make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig
        - name: Build kernel with Bazel
            run: |
                cd android-kernel-5.15
                bazel build //:android_kernel_5.15 --config=arm64
        - name: Build modules with Bazel
            run: |
                cd android-kernel-5.15
                bazel build //:modules --config=arm64
        - name: Install modules
            run: |
                cd android-kernel-5.15
                sudo make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules_install
        - name: Install kernel
            run: |
                cd android-kernel-5.15
                sudo make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- install
        - name: Install modules
            run: |
                cd android-kernel-5.15
                sudo make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules_install
        - name: Install kernel
            run: |
                cd android-kernel-5.15
                sudo make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- install
